### PR TITLE
ccnl-dispatch: externalize ccnl_core_suites

### PR DESCRIPTION
**Pull request by cgundogan**
externalize ccnl_core_suites

### CODE REVIEW

**Comment by mfrey** [comment]
This PR fails with an ``undefined reference to `ccnl_core_suites'`` error. This seems to be the same issue the PR tries to solve?

**Comment by cgundogan** [comment]
Linking problems have been resolved. The only thing failing is the test itself as it seems.

**Comment by mfrey** [comment]
> Linking problems have been resolved. The only thing failing is the test itself as it seems.

That's an easy one. The ``cMatch`` function of ccn-lite was called directly previously instead of using the function pointer (to the cMatch function) in the``ccnl_core_suites``. Your PR makes use of the ``ccnl_core_suites`` but does not check if it has been initialized. The struct needs to be initialized using ``ccnl_core_init()`` beforehand.

**Comment by mfrey** [comment]
@blacksheeep Care to check the CMakeLists.txt? I'm really grateful/happy for Cenks fix, but I'm wondering if there are other ways to resolve these circular dependencies.

**Comment by mfrey** [comment]
Okay, this did not work out as intended. Instead of pushing to your PR, I've created accidentally a new branch on my fork. The fix is over here https://github.com/mfrey/ccn-lite/tree/pr/5

**Review by mfrey — APPROVED** [review]

**Pull request merged**
